### ISSUE TITLE
Remove react-native as a dependency

### ISSUE THREAD

**Issue by itsashis4u** [backpackerds/primitives#10]
As a react-native library, the package shouldn't be dependent on a specific version of react-native. 
I would suggest adding react-native as a peer-dependency with the minimum version the library supports.

**Comment by calintamas** [comment]
@itsashis4u Indeed, thanks! I'll push an update in a few mins

**Comment by calintamas** [comment]
Fixed by d36b050e8a91f1c0ecfb08c45ebc43091fe07d8b
